export const messageResponse: { [key: string]: string } = {
  cannot_access_cms: 'bạn không có quyền truy cập vui lòng liên hệ quản trị viên',
  bad_request: 'Vui lòng kiểm tra lại dữ liệu gửi lên',
  email_invalid: 'Email không hợp lệ',
  phone_number_invalid: 'Số điện thoại không hợp lệ',
  missing_data: 'Thiếu dữ liệu vui lòng kiểm tra lại',
  not_found: 'Đường dẫn',
  duplicate_data: 'Dữ liệu đã tồn tại',
  id_invalid: 'Id không hợp lệ',
  data_invalid: 'Dữ liệu không hợp lệ',
  user_exists: 'User đã tồn tại',
  user_dose_not_exists: 'User không tồn tại',
  user_not_found: 'User không tồn tại',
  password_wrong: 'Sai tài khoản hoặc mật khẩu',
  user_has_blocked: 'Tài khoản đã bị vô hiệu hóa',
  class_has_receive: 'Lớp đã được nhận ',
};
