name: Build, Push Docker, and Deploy

on:
  push:
    tags:
      - "v*" # This pattern matches tags like 'v1.0', 'v2.1', etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version tag
        id: vars
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fe-thglobaltravel:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fe-thglobaltravel:latest

      # - name: Call deployment webhook
      #   run: |
      #     curl -X POST http://103.216.119.69:3000/deploy-webhook \
      #         -H "Content-Type: application/json" \
      #         -d "{\"tag\": \"latest\"}"
